#!/bin/sh

echo $SHELL

######################
# Non-Research Stuff #
######################

rsync -avz /Users/rossknapman/Documents/PhD/* /Users/rossknapman/Seafile/My\ Library/PhDFolderBackup

# Micromagnetic analysis tools
cd /Users/rossknapman/Seafile/TWIST\ ST\ Administrative/BOTH/Software/Data\ Analysis/MicromagneticAnalysisTools && git pull

# Presentations
rsync --delete -avz /Users/rossknapman/Documents/PhD/Presentations /Users/rossknapman/Seafile/P-KE-96_3dSkyrmion_shedding_Ross 

rsync --delete -avz /Users/rossknapman/Documents/PhD/Presentations /Users/rossknapman/Seafile/TWIST\ ST\ Talks\ and\ Posters/Talks\ by\ TWIST\ members/Talks\ by\ Ross\ Knapman


############
# Shedding #
############

rsync -avz --exclude "HelicalShedding/" /Users/rossknapman/Documents/PhD/Projects/Shedding/* /Users/rossknapman/Seafile/P-KE-96_3dSkyrmion_shedding_Ross


##########
# Thesis #
##########

rsync -avz --delete /Users/rossknapman/Documents/PhD/Thesis /Users/rossknapman/Seafile/P-KE-96_3dSkyrmion_shedding_Ross
