#!/bin/sh

#########################################
# Simple Word/Character/Line Count Tool #
#########################################

echo $1 | wc -mlw | awk '{ print "\nWords: " $2 "\tCharacters: " $3 "\tLines: " $1 }'
